---

- name: sauvagaaaaaaarder les routeurs
  hosts: ${PWD##/}/routrs
  tasks:
     - name: commande de conf
       cisco.ios.ios_command:
        commands:
             - write mem
             
