---

- name: sauvagaaaaaaarder les routeurs
  hosts: routrs
  tasks:
     - name: commande de conf
       cisco.ios.ios_command:
        commands:
             - conf t
             - hostname newname
             - exit
             - write mem
             
